language: python
branches:
  only:
  - master
  - develop
matrix:
  include:
  - name: Python 3.7 on Xenial Linux
    python: 3.7
    env:
    - BUILD=True
    dist: xenial
  - name: Python 3.7 on macOS
    os: osx
    osx_image: xcode10.2
    language: shell
before_install:
- make build
install:
- make test-deps
- pip3 install dist/*.whl
script:
- make lint
- make tests
before_deploy:
- cd docs
- make build
- cd ..
deploy:
  matrix:
  - provider: pypi
    user: __token__
    password:
      secure: eJSl2mM90iyRaJH4wzH/nfbxudeOjchOElueJKtcEbKRUlGM1BHNqGiTsSGtU3usbzMFulUjY5+LLC90hOPsbD1u+G/lu3G96FJyUc6+BA6+8SEtS2+Zp+bB3e54DfwYOGaGsM1zFM5N45Shp99npf+OAHi4RaeTN7CQMImKb09AW17iknqLzfy91al+56hakdk2u3b9ZTtyQ3USkkovmUhI+9KhAC3Suha1xuom7qolHMJQVtsMIZzAF7pmhubrEbtS2sbNNk0mv0B7Xya2i3iC+vKgLQwNOSLGr+6JfMLmXLd+KgLvpKlGjcQ2Nm9QohDuNb5QSqnkpKyE6gjyTK/yxO/FNoIxhDzyVtoAp3Y77cIKUO/Bm3hVa/hfKPaZ7aHImIygp0Ew4v1E4VXFXjb9USrXOr2eKICImqaH6EsAaH+sMvg3dXr6OtXH0rpAoMYm5Vw7qbGqx6XFYFJ4yLOSAtMZkwMyuzLMLzQmbJO8rDxPcMT8tMKmQiup632rMA85lnmbrXOzPKEuulqqnhen/s1O0QbHNIyJ9eHDBZtAyUNPQZZ7Mav/mRcSvuh+gKUWaSoYykGUD9EYDQaPTNISPwL0LWu+Yl8zmL6fxpgZqEJDtDrZ1YhFFSVy7xkfbOJix+lqQajOHKv0Gs9oyH7UB5DN5HR0fxggoyc0Z6E=
    distributions: bdist_wheel
    skip_existing: true
    on:
      branch: master
      condition: "$BUILD = True"
  - provider: pages
    skip_cleanup: true
    github_token: "$GITHUB_TOKEN"
    keep_history: true
    local_dir: docs/build/html
    on:
      branch: master
      condition: "$BUILD = True"
